### ISSUE TITLE
Able to bypass max and min

### ISSUE THREAD

**Issue by jh4rri** [uNmAnNeR/ispinjs#1]
Hi,

Even though I have set the max and min in the config options.  If I type into the control, rather than use the buttons, then I am able to set a value outside of the min and max:

https://codepen.io/jharri/pen/wbGgrj

**Comment by uNmAnNeR** [comment]
Hi, 
Yes, spin is only about spin. For restricting input you might use IMaskjs.

**Comment by jh4rri** [comment]
Hi,

Ah, I needed a spinner with input restriction also (so that input and spin work together).

I managed to get something working here:
https://codepen.io/jharri/pen/wbGgrj

**Comment by uNmAnNeR** [comment]
Yes, i got. But in your solution i am still able to input non digits and get NaN.
If you want more strict control for input, you can ispin with [imaskjs](https://github.com/uNmAnNeR/imaskjs):

https://codepen.io/anon/pen/yWJYMR

**Comment by jh4rri** [comment]
ah!  I didn't realise I'd be able to use both on the same element.  Many thanks!
